# Curso básico intensivo de Julia (para MA4702)
## Prof. José Soto

***


# 1. Usando Jupyter

Jupyter trabaja con celdas. Cada celda  puede tener:
1. Texto enriquecido (markdown) ***como esta celda***
2. Código ***como la siguiente celda***


El texto enriquecido, además de formato básico html como **negritas** y *cursivas* permite el uso de $\LaTeX$ escribiendo texto entre signos $

Cosas simples como $\frac{a}{b}=1 \implies (a=b)$, o más complejas como un PL.

Para ejecutar código debe presionar "shift-enter" en la celda (o presionar run en el menú)

In [1]:
1+2+3
1000-1

999

Solo la última celda se imprime. De hecho, si se escribe ; se puede suprimir el resultado de la celda

In [2]:
1+2+3
1000-1;

Si quiere mostrar lo que hace cada linea puede usar @show

In [3]:
@show(1+2+3);
@show(1000-1);

1 + 2 + 3 = 6
1000 - 1 = 999


In [4]:
print("Hola "*" Mundo")

Hola  Mundo

Para ayuda básica, se puede usar ?comando

In [5]:
?print

search: print println printstyled sprint isprint prevind parentindices precision



```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation. The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

`print` falls back to calling `show`, so most types should just define `show`. Define `print` if your type has a separate "plain" representation. For example, `show` displays strings with quotes, and `print` displays strings without quotes.

[`string`](@ref) returns the output of `print` as a string.

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


In [6]:
?*

search: *



```
*(s::Union{AbstractString, AbstractChar}, t::Union{AbstractString, AbstractChar}...) -> AbstractString
```

Concatenate strings and/or characters, producing a [`String`](@ref). This is equivalent to calling the [`string`](@ref) function on the arguments. Concatenation of built-in string types always produces a value of type `String` but other string types may choose to return a string of a different type as appropriate.

# Examples

```jldoctest
julia> "Hello " * "world"
"Hello world"

julia> 'j' * "ulia"
"julia"
```

---

```
*(s::Regex, t::Union{Regex,AbstractString,AbstractChar}) -> Regex
*(s::Union{Regex,AbstractString,AbstractChar}, t::Regex) -> Regex
```

Concatenate regexes, strings and/or characters, producing a [`Regex`](@ref). String and character arguments must be matched exactly in the resulting regex, meaning that the contained characters are devoid of any special meaning (they are quoted with "\Q" and "\E").

!!! compat "Julia 1.3"
    This method requires at least Julia 1.3.


# Examples

```jldoctest
julia> match(r"Hello|Good bye" * ' ' * "world", "Hello world")
RegexMatch("Hello world")

julia> r = r"a|b" * "c|d"
r"(?:a|b)\Qc|d\E"

julia> match(r, "ac") == nothing
true

julia> match(r, "ac|d")
RegexMatch("ac|d")
```

---

```
*(x, y...)
```

Multiplication operator. `x*y*z*...` calls this function with all arguments, i.e. `*(x, y, z, ...)`.

# Examples

```jldoctest
julia> 2 * 7 * 8
112

julia> *(2, 7, 8)
112
```

---

```
*(A::AbstractMatrix, B::AbstractMatrix)
```

Matrix multiplication.

# Examples

```jldoctest
julia> [1 1; 0 1] * [1 0; 1 1]
2×2 Array{Int64,2}:
 2  1
 1  1
```


# 2. Tipos básicos de Julia

## 2.1 Booleanos 

In [7]:
true && false

false

In [8]:
false || true

true

In [9]:
20==21

false

In [10]:
20=="20"

false

In [11]:
!(1==1)

false

## 2.1 Enteros

In [12]:
typeof(55)

Int64

Julia usa enteros de 64 bits 

In [13]:
typemax(Int64)

9223372036854775807

In [14]:
typemax(Int64)+1

-9223372036854775808

In [15]:
typemax(Int64)<Inf

true

In [16]:
rand(1:typemax(Int64)) #entero al azar

8879135675089595204

In [17]:
rand(-12:1)

-11

En aplicaciones, se puede ahorrar espacio usando enteros del tamaño correcto... ¡Con cuidado!

In [18]:
?Int

search: Int Int8 Int64 Int32 Int16 Int128 Integer intersect intersect!



```
Int64 <: Signed
```

64-bit signed integer type.


In [19]:
typemax(Int8)

127

In [20]:
a=Int8(100)
b=Int8(30)
a+b

-126

Tambien hay tipos sin signo, en caso de necesitarlo

In [21]:
?UInt

search: UInt UInt8 UInt64 UInt32 UInt16 UInt128 Cuint Cuintmax_t @uint128_str



```
UInt64 <: Unsigned
```

64-bit unsigned integer type.


Si realmente necesita números grandes, puede usar Big Integers 

In [22]:
?BigInt

search: BigInt disable_sigint reenable_sigint



```
BigInt <: Signed
```

Arbitrary precision integer type.

---

```
BigInt(x)
```

Create an arbitrary precision integer. `x` may be an `Int` (or anything that can be converted to an `Int`). The usual mathematical operators are defined for this type, and results are promoted to a [`BigInt`](@ref).

Instances can be constructed from strings via [`parse`](@ref), or using the `big` string literal.

# Examples

```jldoctest
julia> parse(BigInt, "42")
42

julia> big"313"
313

julia> BigInt(10)^19
10000000000000000000
```


In [23]:
BigInt(10)^35+1

100000000000000000000000000000000001

## 2.2. Punto flotante

In [24]:
typeof(0.559)

Float64

In [25]:
rand() # flotante al azar entre 0 y 1

0.738676896227539

In [26]:
0.2-0.3

-0.09999999999999998

In [27]:
0.2-0.3 == -0.1

false

Con \approx (tab) se obtiene ≈

In [28]:
0.2-0.3 ≈ -0.1

true

In [29]:
typeof(-20.5)

Float64

Otros tipos relacionados:

In [30]:
@show(Float32(30.455)+Float16(20.22));
@show(typeof(Float32(30.455)+Float16(20.22)));

Float32(30.455) + Float16(20.22) = 50.67375f0
typeof(Float32(30.455) + Float16(20.22)) = Float32


Pero cuidado con la precision de punto flotante. Numero flotante es siempre impreciso

In [31]:
0.1

0.1

In [32]:
BigFloat(0.1)

0.1000000000000000055511151231257827021181583404541015625

In [33]:
BigFloat("0.1")

0.1000000000000000000000000000000000000000000000000000000000000000000000000000002

## 2.3 Más tipos numéricos

Julia tiene precargados algunos irracionales, por ejemplo π (escriba \pi y luego presione tab)

In [34]:
π

π = 3.1415926535897...

In [35]:
typeof(π)

Irrational{:π}

In [36]:
BigFloat(π,precision=5000)

3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593344612847564823378678316527120190914564856692346034861045432664821339360726024914127372458700660631558817488152092096282925409171536436789259036001133053054882046652138414695194151160943305727036575959195309218611738193261179310511854807446237996274956735188575272489122793818301194912983367336244065664308602139494639522473719070217986094370277053921717629317675238467481846766940513200056812714526356082778577134275778960917363717872146844090122495343014654958537105079227968925892354201995611212902196086403441815981362977477130996051870721134999999837297804995105973173281609631859502445945534690830264252230825334468503526193118817101000313783875288658753320838142061717766914730359825349042875546873115956286388235378759375195778185778053217122680661300192787661119590921642019

In [37]:
#\euler
ℯ

ℯ = 2.7182818284590...

In [38]:
ℯ - exp(1)

0.0

Tenemos números complejos

In [39]:
(1+im)*(2-im)

3 + 1im

In [40]:
typeof(0.5+2im)

Complex{Float64}

In [41]:
angle(1+im)

0.7853981633974483

In [42]:
abs(1+im)

1.4142135623730951

In [43]:
sin(π/3) == √3/2

true

In [44]:
sin(2π/3) == √3/2

false

In [45]:
sin(2π/3) ≈ √3/2

true

Julia soporta racionales también

In [46]:
typeof(2//3)

Rational{Int64}

In [47]:
6//9

2//3

In [48]:
6//9+12//15

22//15

## 2.4 Strings

In [49]:
s1 = "Hola"; s2 = "Mundo"; s3="😄";
s1*s3*s2

"Hola😄Mundo"

In [50]:
'😄'

'😄': Unicode U+1F604 (category So: Symbol, other)

In [51]:
"$s1, Me dicen $s3"

"Hola, Me dicen 😄"

In [52]:
a=3; b=4

4

In [53]:
string(a)*string(b)

"34"

In [54]:
string(a+b)

"7"

In [55]:
"$a" * "$b"

"34"

In [56]:
"$a+$b"

"3+4"

In [57]:
"$(a+b)"

"7"

# 3 Vectores, Matrices, Arreglos y Diccionarios

Los vectores horizontales se escriben con coeficientes separados por espacios. 
Los verticales separados por comas 

In [58]:
[2 3]

1×2 Array{Int64,2}:
 2  3

In [59]:
b=[2, 3]

2-element Array{Int64,1}:
 2
 3

In [60]:
b[1] # ojo, coordenadas parten de 1...

2

Para matrices usamos punto y coma (coma ya no sirve)

In [61]:
A=[1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [62]:
A[1,1]

1

In [63]:
A[1,1]=5 #Las matrices son "mutables"... se puede cambiar lo que hay dentro

5

In [64]:
ismutable(A)

true

In [65]:
A

2×2 Array{Int64,2}:
 5  2
 3  4

In [66]:
A*b

2-element Array{Int64,1}:
 16
 18

Tenemos algebra lineal. Por ejemplo si queremos resolver A*x=b

In [67]:
x=A\b

2-element Array{Float64,1}:
 0.14285714285714288
 0.6428571428571428

In [68]:
A*x==b

true

In [69]:
@show(b*b')
@show(b'*b);

b * b' = [4 6; 6 9]
b' * b = 13


Si usamos matrices todos los objetos deben ser de la misma "dimension"

In [70]:
["a" 2]

1×2 Array{Any,2}:
 "a"  2

In [71]:
[A 2]

LoadError: DimensionMismatch("mismatch in dimension 1 (expected 2 got 1)")

Se pueden obtener columnas y filas a la Matlab, obteniendo vectores...

In [72]:
A

2×2 Array{Int64,2}:
 5  2
 3  4

In [73]:
A[:,1]

2-element Array{Int64,1}:
 5
 3

In [74]:
A[2,:]

2-element Array{Int64,1}:
 3
 4

In [75]:
A[2,:]'

1×2 LinearAlgebra.Adjoint{Int64,Array{Int64,1}}:
 3  4

Para coleccionar "cosas", se pueden usar tuplas

In [76]:
t=("a", A, 2, b)

("a", [5 2; 3 4], 2, [2, 3])

In [77]:
typeof(t)

Tuple{String,Array{Int64,2},Int64,Array{Int64,1}}

In [78]:
t[4]

2-element Array{Int64,1}:
 2
 3

In [79]:
size(t,1)

4

Tambien podemos "desempaquetar una tupla"

In [80]:
t

("a", [5 2; 3 4], 2, [2, 3])

In [81]:
x,y,z,w = t;
y

2×2 Array{Int64,2}:
 5  2
 3  4

In [82]:
# las tuplas no son mutables
ismutable(t)

false

In [83]:
t[4]=0

LoadError: MethodError: no method matching setindex!(::Tuple{String,Array{Int64,2},Int64,Array{Int64,1}}, ::Int64, ::Int64)

Si se quiere dar sentido, a las coordenadas de las tuplas se les pueden dar nombres

In [84]:
t2=(nombre="Alejandro", matriz=[2 2; 1 1], favorito=π)

(nombre = "Alejandro", matriz = [2 2; 1 1], favorito = π)

In [85]:
t2.favorito

π = 3.1415926535897...

También se pueden crear diccionarios (similar a Python)

In [86]:
d1=Dict("A"=>1, "B"=>4, "CDE"=>5)

Dict{String,Int64} with 3 entries:
  "B"   => 4
  "A"   => 1
  "CDE" => 5

In [87]:
d1["CDE"]

5

# 4 Iteradores y control de flujo

In [88]:
for i in 1:5
    println(i)
end

1
2
3
4
5


In [89]:
for j in [1 2 8 "casa" "😸"]
    println(j)
end

1
2
8
casa
😸


In [90]:
for i in 4:10:100
    println(i)
end

4
14
24
34
44
54
64
74
84
94


In [91]:
suma=0
for (key,value) in Dict("A"=>1, "B"=>5, "C"=>0+5im)
    println("Revisando $key")
    suma+=value
end
println("La suma es $suma")

Revisando B
Revisando A
Revisando C
La suma es 6 + 5im


Tambien tenemos if, elseif, else; while, 

In [92]:
for i in 0:2:14
    if i < 5 
        println("$(i) is menor que 6")
    elseif i < 10
        println("$(i) is menor que 10 y mayor o igual que 6")
    else
        if i == 10
            println("$(i) es 10")
        else
            println("$(i) es más que 10")
        end
    end
end

0 is menor que 6
2 is menor que 6
4 is menor que 6
6 is menor que 10 y mayor o igual que 6
8 is menor que 10 y mayor o igual que 6
10 es 10
12 es más que 10
14 es más que 10


In [93]:
i = 1;
while i <= 5
    println(i)
    global i += 1 #global... pues i fue definido fuera de while
end

1
2
3
4
5


## 5 Comprensión, grafos rudimentarios

Podemos crear arreglos usando iteradores

In [94]:
[i*j for i in 1:5, j in 5:10]

5×6 Array{Int64,2}:
  5   6   7   8   9  10
 10  12  14  16  18  20
 15  18  21  24  27  30
 20  24  28  32  36  40
 25  30  35  40  45  50

In [95]:
[i for i in 10:50 if i%3==0]

13-element Array{Int64,1}:
 12
 15
 18
 21
 24
 27
 30
 33
 36
 39
 42
 45
 48

In [96]:
sum(i for i in 10:50 if i%3==0)

390

Esto es importante para PL pues necesitaremos sumas


In [97]:
G = [
    0 100 30  0  0;
    0   0 20  0  0;
    0   0  0 10 60;
    0  15  0  0 50;
    0   0  0  0  0;
] # representa los pesos de un digrafo de 5x5

5×5 Array{Int64,2}:
 0  100  30   0   0
 0    0  20   0   0
 0    0   0  10  60
 0   15   0   0  50
 0    0   0   0   0

In [98]:
sum(G[:,2]) # suma de los pesos de aristas que entran a 2

115

In [99]:
sum(G[i,j] for i in 2:3, j in 3:5)

90

In [100]:
sum(G[i,j] for i in 2:3, j in 3:5 if G[i,j]!=60)

30

Si bien existen paquetes para trabajar con grafos no dirigidos (tal vez los usemos). Podemos representar un grafo manualmente como una lista de incidencia imponiendo i<j... por ejemplo


In [101]:
vertices=1:8
aristas=[(1,1) (1,2) (1,3) (2,4) (3,5) (4,5) (4,8) (5,7) (7,8)]
pesos=Dict((i,j)=>rand(10:100) for (i,j) in aristas)

Dict{Tuple{Int64,Int64},Int64} with 9 entries:
  (4, 5) => 32
  (4, 8) => 30
  (5, 7) => 80
  (1, 2) => 95
  (7, 8) => 94
  (2, 4) => 57
  (1, 1) => 35
  (1, 3) => 20
  (3, 5) => 86

Suma de los pesos de las aristas incidentes a 4?

In [102]:
[(i,j,pesos[i,j]) for (i,j) in aristas if (i==4 || j==4)]

3-element Array{Tuple{Int64,Int64,Int64},1}:
 (2, 4, 57)
 (4, 5, 32)
 (4, 8, 30)

In [103]:
sum(pesos[i,j] for (i,j) in aristas if (i==4 || j==4))

119

## 6 Funciones

Funciones siempre con ().

In [104]:
function saluda()
    println("hola")
    return("chao");
end

saluda (generic function with 1 method)

In [105]:
A=saluda();

hola


In [106]:
A

"chao"

In [107]:
function duplica(x)
    return x*2
end
    

duplica (generic function with 1 method)

In [108]:
duplica(20)

40

In [109]:
duplica(1+im)

2 + 2im

In [110]:
duplica("a")

LoadError: MethodError: no method matching *(::String, ::Int64)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:538
  *(::Missing, ::Number) at missing.jl:115
  *(::Complex{Bool}, ::Real) at complex.jl:309
  ...

funciones con valores opcionales

In [111]:
function multiplica(x; y=2)
    return x * y
end

multiplica (generic function with 1 method)

In [112]:
multiplica(50.2)

100.4

In [113]:
multiplica(50.2; y=3)

150.60000000000002

# 7 Paquetes

Necesitaremos llamar a paquetes adicionales de Julia. Algunos vienen preinstalados...

In [114]:
A=[1 1; 1 1]

2×2 Array{Int64,2}:
 1  1
 1  1

In [115]:
tr(A)


LoadError: UndefVarError: tr not defined

In [116]:
using LinearAlgebra

In [117]:
tr(A)

2

In [118]:
eigvals(A)

2-element Array{Float64,1}:
 0.0
 2.0

Otros.. como JuMP se deben instalar (solo una vez)

In [119]:
import Pkg
Pkg.add("JuMP")

   Updating registry at `C:\Users\Jose\.julia\registries\General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


Fetching: [========================================>]  100.0 %  75.3 %Fetching: [=====================================>   ]  92.5 %

  Resolving package versions...
No Changes to `C:\Users\Jose\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\Jose\.julia\environments\v1.5\Manifest.toml`


luego se pueden usar escribiendo

In [120]:
using JuMP